kind: pipeline
type: kubernetes
name: drone-kaniko

metadata:
  namespace: cicd

trigger:
  ref:
    include:
      - refs/tags/release-*

steps:
- name: build
  image: golang:1.21
  commands:
  - go test ./...
  - sh scripts/build.sh

- name: docker
  image: plugins/docker
  settings:
    repo: plugins/kaniko
    auto_tag: true
    auto_tag_suffix: linux-amd64
    daemon_off: false
    dockerfile: docker/docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      exclude:
      - pull_request
